services:
  controller:
    image: ghcr.io/open-traffic-generator/keng-controller:1.13.0-1
    command: --accept-eula --http-port 8443
    network_mode: "host"
    restart: always
  traffic_engine_1:
    image: ghcr.io/open-traffic-generator/ixia-c-traffic-engine:1.8.0.25
    restart: always
    privileged: true
    network_mode: "host"
    ports:
      - "5551:5551"
      - "50071:50071"
    environment:
      - OPT_LISTEN_PORT=5551
      - ARG_IFACE_LIST=virtual@af_packet,veth0 virtual@af_packet,veth1
      - OPT_NO_HUGEPAGES=Yes
      - OPT_NO_PINNING=Yes
      - WAIT_FOR_IFACE=Yes
  protocol_engine_1:
    image: ghcr.io/open-traffic-generator/ixia-c-protocol-engine:1.00.0.399
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - INTF_LIST=veth0,veth1
